language: python

python:
  - "3.7.0"
  - "3.6.4"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - source ./.travis.sh

script:
  - coverage run -m pytest -v

after_success:
  - coveralls
  
notifications:
  email: false
