language: python

python:
  - "3.6.4"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - source ./.travis.sh

script:
  - nosetests -sv tests --with-coverage app/ instance/config

after_success:
  - coveralls

notifications:
  email: false
